//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQHospital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpatient
    {
        public int Id { get; set; }
        public string PatientName { get; set; }
        public string PatientMobile { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public Nullable<int> DocId { get; set; }
    }
}
